[2025-08-24T19:32:14.300+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl.transform_weather manual__2025-08-24T19:32:12.291093+00:00 [queued]>
[2025-08-24T19:32:14.309+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl.transform_weather manual__2025-08-24T19:32:12.291093+00:00 [queued]>
[2025-08-24T19:32:14.310+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-24T19:32:14.324+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_weather> on 2025-08-24 19:32:12.291093+00:00
[2025-08-24T19:32:14.330+0000] {standard_task_runner.py:60} INFO - Started process 182 to run task
[2025-08-24T19:32:14.334+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_etl', 'transform_weather', 'manual__2025-08-24T19:32:12.291093+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl.py', '--cfg-path', '/tmp/tmpp6x0rzth']
[2025-08-24T19:32:14.337+0000] {standard_task_runner.py:88} INFO - Job 15: Subtask transform_weather
[2025-08-24T19:32:14.422+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_etl.transform_weather manual__2025-08-24T19:32:12.291093+00:00 [running]> on host 7b1c3b0dd09a
[2025-08-24T19:32:14.589+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl' AIRFLOW_CTX_TASK_ID='transform_weather' AIRFLOW_CTX_EXECUTION_DATE='2025-08-24T19:32:12.291093+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-24T19:32:12.291093+00:00'
[2025-08-24T19:32:14.608+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-08-24T19:32:14.615+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_etl, task_id=transform_weather, execution_date=20250824T193212, start_date=20250824T193214, end_date=20250824T193214
[2025-08-24T19:32:14.666+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-24T19:32:14.682+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
