[2025-08-24T20:00:42.574+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl.load_raw_new_york manual__2025-08-24T20:00:40.718194+00:00 [queued]>
[2025-08-24T20:00:42.584+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl.load_raw_new_york manual__2025-08-24T20:00:40.718194+00:00 [queued]>
[2025-08-24T20:00:42.585+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-24T20:00:42.599+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_raw_new_york> on 2025-08-24 20:00:40.718194+00:00
[2025-08-24T20:00:42.604+0000] {standard_task_runner.py:60} INFO - Started process 188 to run task
[2025-08-24T20:00:42.610+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_etl', 'load_raw_new_york', 'manual__2025-08-24T20:00:40.718194+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl.py', '--cfg-path', '/tmp/tmpbnyzbzmh']
[2025-08-24T20:00:42.612+0000] {standard_task_runner.py:88} INFO - Job 36: Subtask load_raw_new_york
[2025-08-24T20:00:42.709+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_etl.load_raw_new_york manual__2025-08-24T20:00:40.718194+00:00 [running]> on host 7b1c3b0dd09a
[2025-08-24T20:00:42.850+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl' AIRFLOW_CTX_TASK_ID='load_raw_new_york' AIRFLOW_CTX_EXECUTION_DATE='2025-08-24T20:00:40.718194+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-24T20:00:40.718194+00:00'
[2025-08-24T20:00:42.879+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-08-24T20:00:42.892+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_etl, task_id=load_raw_new_york, execution_date=20250824T200040, start_date=20250824T200042, end_date=20250824T200042
[2025-08-24T20:00:42.948+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-24T20:00:42.996+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
